### ISSUE TITLE
"New" macOS nightlies fail to execute (signing problem?)

### ISSUE THREAD

**Issue by maleadt** [JuliaCI/julia-buildkite#124]
The old, 1-month nightlies at //julialangnightlies-s3.julialang.org/bin/mac/x64/julia-latest-mac64.dmg can be successfully opened on my M1 mac with SIP enabled after mounting the dmg. The "new" ones at http://julialangnightlies-s3.julialang.org/bin/macos/x64/julia-latest-macos64.dmg, which are available since https://github.com/JuliaCI/julia-buildkite/issues/122, do not:

![image](https://user-images.githubusercontent.com/383068/170653168-6770cf08-7a17-49c5-8935-46a7281f66e5.png)

Control-click+open doesn't work because then the initial 'script' gets to run, but subsequent binaries or libraries are still prevented from executing.

**Comment by DilumAluthge** [comment]
@staticfloat @gbaraldi

**Comment by DilumAluthge** [comment]
Are we using Buildkite for the macOS binaries for 1.8? If so, this issue is a 1.8 release blocker.

**Comment by staticfloat** [comment]
It's not a release blocker, because we manually notarize the releases.

I've added automatic notarization here: https://github.com/JuliaCI/julia-buildkite/pull/133

**Comment by maleadt** [comment]
Yup, both tarballs and the dmg execute fine now. Thanks!
