### ISSUE TITLE
Meta-issue: FreeBSD

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildkite#26]
Next steps:

> We need a sandbox.  Alex Arslan has supposedly been researching whether FreeBSD jails can be used to give us something like what we have on macOS.  I’m not worried about this until we get the story on the three previous points solid.

**Comment by ararslan** [comment]
Notes for myself so I don't keep forgetting what this issue actually entails. The sandbox environment, at a minimum, needs to be able to:
- Exist as an isolated environment on the host
- Let the host system manage a Julia process executing inside of the sandbox
- Be torn down without leaving a trace
- Use a specified tarball containing the root filesystem

It's relatively easy to Just™ start up a minimal ephemeral jail on the host that runs the same OS. This is described a bit in the documentation for the FreeBSD Lua extension (`flua`) [interface to `libjail.so`](https://github.com/freebsd/freebsd-src/tree/main/lib/flua/libjail). The custom root filesystem part is a bit more complicated but is actually directly supported. A painfully comprehensive description of jail setup and management is available in the [handbook](https://docs.freebsd.org/en/books/handbook/jails/). Handling OS installation in a jail can be done by [`bsdinstall`](https://www.freebsd.org/cgi/man.cgi?bsdinstall(8)).

**Comment by DilumAluthge** [comment]
Here's the other thing that, while not strictly a requirement, would be really nice to have.

When we enter the jail, we'd like to mount the root filesystem image as read-only, and then overlay a tempfs on top. All modifications are made to the tempfs; the root filesystem is immutable. When the job ends, the tempfs is destroyed.

**Comment by ararslan** [comment]
Ah, good to know. Breadcrumb to tmpfs on FreeBSD: [man 5 tmpfs](https://www.freebsd.org/cgi/man.cgi?query=tmpfs&sektion=&n=1). I think we configure the jail to load the relevant kernel module on jail startup.

**Comment by ararslan** [comment]
Actually, why is a mutable temporary filesystem necessary inside of a jail? The jail itself is the temporary environment that gets destroyed at the end of a job.

**Comment by DilumAluthge** [comment]
We don't want to modify the root filesystem image, because we want to re-use it in future jobs.

**Comment by ararslan** [comment]
Right, that's already solved in two ways by the design of jails:
1. Jail templates. When you start a new jail, you can tell it the template to use for the system so that you can tear down and recreate similar images over and over.
2. Multi-user systems. That is, the user inside the jail doesn't have to be root. (In fact, I think it isn't by default.)

**Comment by ararslan** [comment]
FreeBSD support has landed in sandboxed-buildkite-agent! Per Elliot, the next step is to take [the macOS build pipeline](https://github.com/JuliaCI/julia-buildkite/blob/main/pipelines/main/platforms/build_macos.yml), adapt it for FreeBSD, and add it [here](https://github.com/JuliaCI/julia-buildkite/blob/2ee095b0fe4322929c86f75249c819beff9ee219/pipelines/main/launch_unsigned_jobs.yml#L34-L38).

**Comment by staticfloat** [comment]
It's working, although we do have some bugs with the agent shutdown code.
