### ISSUE TITLE
Meta-issue: macOS

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/julia-buildkite#27]
Current status and next steps:

> Sandboxing works (barely tested) and we have build agents running, but not building Julia.  The [sandboxing works via “seatbelt”](https://github.com/JuliaCI/sandboxed-buildkite-agent/tree/main/macos-seatbelt), the built-in app sandboxing that macOS provides, and it basically marks certain parts of the system as read-only.  There [was a PR to build Julia using these workers](https://github.com/JuliaLang/julia/pull/43529), but it hasn’t been merged yet.  For reproducibility, we’d like to develop a way to stuff a macOS toolchain into a .tar.gz file and distribute it as an artifact, then deploy that onto the macOS workers on-demand, JLL style.  That will require some playing around.

**Comment by DilumAluthge** [comment]
@staticfloat @gbaraldi Can this issue be closed? AFAICT, except for the segfaults (https://github.com/JuliaLang/julia/issues/44562), macOS CI is working well on both Intel and Apple Silicon.

**Comment by DilumAluthge** [comment]
Oh, I guess this part is not done yet:

> For reproducibility, we’d like to develop a way to stuff a macOS toolchain into a .tar.gz file and distribute it as an artifact, then deploy that onto the macOS workers on-demand, JLL style. That will require some playing around.

**Comment by staticfloat** [comment]
I'm closing this for now, as what we have has been working fairly well for us so far.
