### ISSUE TITLE
Switch from altool to notarytool

### ISSUE THREAD

**Issue by Keno** [JuliaCI/julia-buildkite#306]
The former is deprecated (https://developer.apple.com/documentation/technotes/tn3147-migrating-to-the-latest-notarization-tool?changes=_3_3)

We used this here:
https://github.com/JuliaCI/julia-buildkite/blob/61513b36584fb3b06626e9c246b42b5ec4f0cc61/utilities/macos/build_dmg.sh#L61-L120

We need to do this before November, when Apple will shut down the old API.

**Comment by DilumAluthge** [comment]
Thanks for reporting this!

@gbaraldi Would you be able to look into this?

**Comment by gbaraldi** [comment]
Sure, I'll take a look
