### ISSUE TITLE
promote i686 and gcext to must-pass

### ISSUE THREAD

**Issue by vtjnash** [JuliaCI/julia-buildkite#325]
We want people to make sure these 3 configurations are passing, and not blindly trust the ✅ on the PR:

:linux:[ test i686-linux-gnunet](https://buildkite.com/julialang/julia-master/builds/30171#018bd99e-c8e2-4acd-b41d-aa11ff9aac75)
:linux:[ test i686-linux-gnu](https://buildkite.com/julialang/julia-master/builds/30171#018bd99e-c448-4fca-8349-6e61c389e03c)
:linux:[ test gcext](https://buildkite.com/julialang/julia-master/builds/30171#018bd99e-e43d-4b00-b9bc-5b6cbce49d9c)

**Comment by DilumAluthge** [comment]
The i686 tests used to be red all the time. Are they stable these days?

**Comment by vtjnash** [comment]
Fixed by https://github.com/JuliaLang/julia/pull/52182

**Comment by vtjnash** [comment]
bump. this would have caught an error recently (https://github.com/JuliaLang/julia/issues/53025)

**Comment by IanButterworth** [comment]
Opened a PR to promote 2/3 https://github.com/JuliaCI/julia-buildkite/pull/344

**Comment by IanButterworth** [comment]
Should`test x86_64-unknown-freebsd` be promoted too? I haven't found a failure on master on recent commits
