### ISSUE TITLE
Documenter making builds fail on julia-buildkite repo CI

### ISSUE THREAD

**Issue by IanButterworth** [JuliaCI/julia-buildkite#336]
https://github.com/JuliaCI/julia-buildkite/pull/332#issuecomment-1917950993

Making this an issue so we can track it. 
cc. @mortenpi

**Comment by mortenpi** [comment]
I would put the "blame" here on the CI scripts though. It looks like the [code is getting checked out in a weird way](https://github.com/JuliaCI/julia-buildkite/pull/332#issuecomment-1918160653), and so it breaks `doc/make.jl`, which assume a standard checkout. Of course, we might be able to adapt `doc/make.jl` to make this work somehow, but I don't really have a sense what the differences are between a standard Julia checkout and what the CI does.
